### ISSUE TITLE
タグ用のテーブルを作成

### ISSUE THREAD

**Issue by KishiKyousuke** [ChisatoMatoba/odekake-with-dogs#33]
## 概要
投稿に紐付けるタグ用のテーブルを作成する。
N対Nの構造で作成する。

## やること
- タグ用のテーブルおよび中間テーブルを作成する
  - タグのテーブルに必要なカラムはname（それ以外に必要なものがあれば追加してください）

**Comment by ChisatoMatoba** [comment]
テーブル作成の前にER図を作ってみましたので、認識合っているかご確認頂きたいです。

![OwD_ER](https://github.com/ChisatoMatoba/odekake-with-dogs/assets/149556430/2da95dd8-b719-4737-a7c1-1afa0e480b1d)
