### ISSUE TITLE
検索フォームのビューイメージ作成

### ISSUE THREAD

**Issue by ChisatoMatoba** [ChisatoMatoba/odekake-with-dogs#67]
## 概要
検索機能を実装する前に、検索フォームのビューイメージを作成し、認識合わせをしておく

## やること
- ransack gemの導入
　参考にする予定のQiita記事：[Rubyon Rails で検索機能を作ろう（ransack）](https://qiita.com/nojinoji/items/e1b174220da8c81a1756)
- root_path(Post#index)に検索フォームを作成する
- 検索結果部分には、一旦全投稿を一覧表示するsectionを新たに作っておく
　(以前のフォトギャラリーは、モーダル表示などのbootstrapや地域のタブ表示などが複雑に入り組んでいるので、今回の検索機能実装とは切り分けたいため)
![image](https://github.com/ChisatoMatoba/odekake-with-dogs/assets/149556430/57c9a7d5-8add-4d94-9a67-6dddf68248f4)

- PR時に、簡単に今後の実装方針も提出し、方向性が大きくずれていないか、もレビューする

## やらないこと
- controller等は変更しない
- search_form_forの記載の仕方などで致命的に間違っている部分以外は、細かく指摘不要

**Comment by ChisatoMatoba** [comment]
ビューイメージを作成しましたので、ご確認よろしくお願いいたします。
イメージの下に仕様のイメージも記載していますので、もし認識違いや助言あればお願いいたします。

![検索フォームイメージ](https://github.com/ChisatoMatoba/odekake-with-dogs/assets/149556430/63aeb64f-47bb-4533-90c3-851dc557393d)

### 検索フォームについて
- 施設テーブルに紐づいている条件(都道府県〜施設の条件まで)は、「条件に一致する施設と紐付けられている投稿」を結果として表示する
- 選択したものはすべてAND検索、「---」の場合は検索条件から除外
- 各検索条件に対してissueを立てているので、それぞれのissueごとに1つずつ実装していき、それ以前に実装済みの検索とANDとなるようにしていく
- タグの絞り込み、キーワード検索の詳細仕様は未定（スケジュールにより難易度相談？）

### 検索結果の機能拡張について
- 上記ビューイメージの検索結果の下(白枠背景部分)が今回追加予定のイメージ
- 並び順の項目については未定(決まり次第issueで記載する)

**Comment by KishiKyousuke** [comment]
@ChisatoMatoba 
良い感じだと思います:+1:

> 選択したものはすべてAND検索、「---」の場合は検索条件から除外

ここに関しては修正自体は簡単にできると思うので、以下のIssueを先に対応するのもありかな〜と思っています。

https://github.com/ChisatoMatoba/odekake-with-dogs/issues/4
