### ISSUE TITLE
dockerの導入

### ISSUE THREAD

**Issue by naomichihorimoto** [ChisatoMatoba/odekake-with-dogs#8]
## 目標
- dockerおよびコンテナの概念を学ぶ
- dockerを導入し、コンテナ化したアプリを動作させる

## 作業内容
課題1と2を行ってください

### dockerおよびコンテナの概念を学ぶ
参考文献やドットインストール、Udemy、chatGPTなどを利用して、dockerとコンテナの基礎と概念を抑えてください（課題1と合わせて1.5人日くらいを目安とし、課題2のマージ完了までで3.0人日を予定しています）

以下を説明できれば、アプリのdocker化はできると思います
- イメージとコンテナ
- Dockerfileとdocker-compose.ymlの役割
- Dockerfileとdocker-compose.ymにはそれぞれ何を記述するか
- docker engineの役割
- マシン上でdockerコンテナが動いている全体像
- `docker compose exec` と `docker compose run` の違い
- コンテナに環境変数を設定する方法
- volumeとマウント
- docker上でコンソールを開く方法

※ 参考文献に置いたQiitaの記事から入ることをおすすめします。構築に必要な知識に絞って紹介されており、わかりやすいので、一気にイメージが掴めると思います

### [課題1] Qiitaの参考文献を見ながらRailsの環境構築をする 
環境構築の後、docker compose up時のdockerのログのスクショと、Dockerfile、docker-compose.ymlをこのissueのコメントに添付してください

また、dbイメージはMysql、Ruby, Railsのバージョンをodekake with dogsと揃えるようにしてください

#### 参考文献
DockerでRails環境構築
https://qiita.com/Yusuke_Hoirta/items/3a50d066af3bafbb8641

公式
https://docs.docker.com/

公式マニュアルの日本語訳
https://docs.docker.jp/

### [課題2] odekake with dogsにdockerを導入し、コンテナ化したアプリを動作させる
odekake with dogsをdocker化し、PRを作成してレビュー依頼を出してください
`docker compose up` でアプリが動作していることを確認できればokです

主に以下の手順で進むことになると思います
1. docker desktopのインストール（dockerおよびコンテナの概念を学ぶ段階でインストール済）
2. Dockerfileの記述
3. docker-compose.ymlの記述
4. 動作確認

## 備考
docker composeは、version1とversion2で、docker-compose.ymlの書き方の違いや、コマンドの違い等があります
version1はすでにEOLなので、version2の方を学ぶのが良いですが、案件では、version1に則っている可能性もあります
研修ではverision1とversion2があって、違いがあるんだな。ぐらいを抑えておいて、案件内でその都度対応する感じでokです

参考：https://qiita.com/zembutsu/items/d82b2ae1a511ebd6a350

**Comment by ChisatoMatoba** [comment]
> 課題1について、 buildまではできたのですが、docker-compose upをしたら、webの方だけupされずにexitedになってしまいます。 `docker-compose logs web`でログを見たところ、以下のエラーがありました。
> 
> ```
> ログから抜粋
> web-1  | /usr/local/bundle/ruby/3.1.0/gems/railties-7.1.2/lib/rails/application.rb:655:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)
> ```

記録のためのコメント残しておきます。
本件、product仕様になっていたものをdevelopment仕様に変更したのにエラーが出ていましたが、buildするときにキャッシュを削除してから実行すると、修正後の内容が反映されてエラーが解消されました。

```sh
docker-compose build --no-cache
```

**Comment by ChisatoMatoba** [comment]
昨日はありがとうございました。
自分のまとめ用に、改めて別の架空アプリ(myapp)で事象をまとめながら再実行してみました。
こちらの方が見やすいと思うので、こちらの[readme](https://github.com/ChisatoMatoba/docker_test#:~:text=1%20hour%20ago-,README.md,-first%20commit)でご確認いただけますでしょうか。
https://github.com/ChisatoMatoba/docker_test


※昨日は何も分かっていなかったので謎に終わってしまいましたが、rails7.1からの変更で
`docker-compose run web rails new`で`Dockerfile`が本番環境仕様に自動生成されていたのが大きな原因でした。

[Docker + Rails7.1 の環境構築で詰まったポイント](https://zenn.dev/yoiyoicho/articles/90e1ea64772ea8)

[Ruby on Rails 7.1の主要な新機能・機能追加・変更点](https://qiita.com/ryohashimoto/items/ed669f2e529d489e9fe4#:~:text=Ruby%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9FOSS,%E3%81%AB%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E3%81%95%E3%82%8C%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82)
※rails7.1は2023/10/5リリースらしいので、このissueはかなりホットな問題だったんですね！笑

[Ruby on Rails 7.1 リリースノート：新規RailsアプリケーションでDockerfileが生成されるようになった](https://railsguides.jp/7_1_release_notes.html#%E6%96%B0%E8%A6%8Frails%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A7dockerfile%E3%81%8C%E7%94%9F%E6%88%90%E3%81%95%E3%82%8C%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F)
