### ISSUE TITLE
施設テーブルの作成

### ISSUE THREAD

**Issue by KishiKyousuke** [ChisatoMatoba/odekake-with-dogs#9]
## 概要
新たに施設テーブルを作成・施設モデルを作成し投稿に関連づける。
施設条件は施設とhas_manyの関連で、ActiveHash定義に変更しても良いかも。

- 投稿テーブルから切り出せるカラムは以下
  - 都道府県
  - 施設名
  - カテゴリー
  - 満足度（これはお出かけの満足度なら投稿、施設の満足度なら施設に置く感じでOK）

## やること
- 施設テーブルの作成
- 施設モデルの作成
- 施設条件のActiveHashのclassを作成
  - 施設と関連付け

## やらないこと
- 投稿テーブルからのカラム削除や、施設条件テーブルの削除は現段階では不要です（消すとアプリが動かなくなるため）

**Comment by ChisatoMatoba** [comment]
#12 施設テーブル・モデルの作成が完了しましたので、ご確認よろしくお願いいたします。
